boot.o: boot.S multiboot.h x86_desc.h types.h
keyboardWrapper.o: keyboardWrapper.S
pagingasm.o: pagingasm.S
scheduler_asm.o: scheduler_asm.S
syscall_asm.o: syscall_asm.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesystem.o: filesystem.c filesystem.h lib.h types.h multiboot.h \
  terminal.h keyboard.h i8259.h syscall.h paging.h pcb.h x86_desc.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h lib.h types.h scheduler.h pcb.h filesystem.h \
  multiboot.h paging.h terminal.h keyboard.h i8259.h syscall.h x86_desc.h \
  rtc.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  paging.h pcb.h filesystem.h terminal.h keyboard.h syscall.h idt.h \
  scheduler.h rtc.h
keyboard.o: keyboard.c keyboard.h lib.h types.h i8259.h terminal.h \
  filesystem.h multiboot.h pcb.h paging.h syscall.h x86_desc.h
lib.o: lib.c lib.h types.h terminal.h keyboard.h i8259.h syscall.h \
  paging.h pcb.h filesystem.h multiboot.h x86_desc.h
paging.o: paging.c paging.h types.h lib.h pcb.h filesystem.h multiboot.h \
  terminal.h keyboard.h i8259.h syscall.h x86_desc.h
pcb.o: pcb.c pcb.h lib.h types.h filesystem.h multiboot.h terminal.h \
  keyboard.h i8259.h syscall.h paging.h x86_desc.h
rtc.o: rtc.c rtc.h lib.h types.h filesystem.h multiboot.h i8259.h
scheduler.o: scheduler.c scheduler.h lib.h types.h pcb.h filesystem.h \
  multiboot.h paging.h terminal.h keyboard.h i8259.h syscall.h x86_desc.h
syscall.o: syscall.c syscall.h types.h terminal.h lib.h keyboard.h \
  i8259.h filesystem.h multiboot.h pcb.h paging.h x86_desc.h
terminal.o: terminal.c terminal.h lib.h types.h keyboard.h i8259.h \
  syscall.h paging.h pcb.h filesystem.h multiboot.h x86_desc.h
